import = [
"~/.config/alacritty/themes/tokyo-night.toml"
]

[window]
opacity = 0.8
# decorations = "none"
dimensions = { columns =90 , lines =30 }
padding = {x=0, y=0}
dynamic_padding = true

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 12.0
# glyph_offset = {x=0, y=2}
# offset= { x =0, y=3}

[cursor]    
style = { shape = "Block", blinking = "Always" }
thickness = 0.20

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
# args = ["-l", "-c", "tmux attach || tmux new -s dev"]
